### ISSUE TITLE
Prompt to choose gpgsign key on setup

### ISSUE THREAD

**Issue by DrSensor** [DrSensor/gitmanager#1]
## Implementation
- [ ] Multiselect which operation to use `gpgsign`
```sh
git config push.gpgsign if-asked
git config commit.gpgsign true
git config tag.gpgsign true
```
- [ ] Select `signingkey` from `list-secret-keys`
```sh
gpg --list-secret-keys --keyid-format long
git config user.signingkey 0123346789ABCDEF
git config user.name Spam Killer
git config user.email spamkiller@dispossable.email
```

## Usage
- [ ] Automatic from url or path
```sh
git setup https://github.com/cli/cli

# or for existing repo
git setup

# works with multiple repos too
git setup ~/Projects/OSS/{ repo1, repo2 }
```
- [ ] Manual on specific branches and/or tags
```sh
git setup --gpgsign hotfix/big-bug feature/branch
```
- [ ] Support wildcards (handy for tags)
```sh
git setup --signingkey 'v3.0.0-[alpha|beta].*'
```
- [ ] `--gpgsign` and `--signingkey` should be the same (to avoid confusion)
